package main

import (
	"crypto/tls"
	"crypto/x509"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

const (
	// Default certificate names generated by: mkcert localhost 127.0.0.1 ::1
	serverCertFile = "localhost+2.pem"
	serverKeyFile  = "localhost+2-key.pem"
	listenAddr     = ":8443" // Port to listen on (requires no special privileges)
)

// findMkcertCARoot uses the `mkcert -CAROOT` command to find the CA path.
func findMkcertCARoot() (string, error) {
	cmd := exec.Command("mkcert", "-CAROOT")
	output, err := cmd.Output()
	if err != nil {
		// Provide more context if mkcert isn't found
		if ee, ok := err.(*exec.Error); ok && ee.Err == exec.ErrNotFound {
			return "", fmt.Errorf("'mkcert' command not found in PATH. Please ensure mkcert is installed and accessible: %w", err)
		}
		return "", fmt.Errorf("failed to run 'mkcert -CAROOT': %w", err)
	}
	// Trim whitespace, as the command might add a newline
	caPath := strings.TrimSpace(string(output))
	if caPath == "" {
		return "", fmt.Errorf("'mkcert -CAROOT' returned an empty path")
	}
	return caPath, nil
}

// simple mTLS authenticated handler
func helloHandler(w http.ResponseWriter, r *http.Request) {
	// Client certificate details are available in r.TLS.PeerCertificates
	clientName := "Unknown Client"
	if r.TLS != nil && len(r.TLS.PeerCertificates) > 0 {
		// Use CommonName if available, otherwise fallback to the full Subject
		cn := r.TLS.PeerCertificates[0].Subject.CommonName
		if cn != "" {
			clientName = cn
		} else {
			clientName = r.TLS.PeerCertificates[0].Subject.String()
		}
		log.Printf("Authenticated client: Subject='%s', Issuer='%s'", r.TLS.PeerCertificates[0].Subject, r.TLS.PeerCertificates[0].Issuer)
	} else {
		log.Println("Authenticated client: No peer certificate information found (this shouldn't happen with RequireAndVerifyClientCert)")
	}

	w.Header().Set("Content-Type", "text/plain")
	fmt.Fprintf(w, "Hello World! mTLS authentication successful for: %s\n", clientName)
}

func main() {
	fmt.Println("--- mTLS Hello World Server ---")

	// --- 1. Check for mkcert server certificate and key ---
	fmt.Printf("Checking for server certificate (%s) and key (%s)...\n", serverCertFile, serverKeyFile)
	if _, err := os.Stat(serverCertFile); os.IsNotExist(err) {
		log.Fatalf("❌ Server certificate '%s' not found in the current directory.\n   Please run: mkcert localhost 127.0.0.1 ::1", serverCertFile)
	}
	if _, err := os.Stat(serverKeyFile); os.IsNotExist(err) {
		log.Fatalf("❌ Server key '%s' not found in the current directory.\n   Please run: mkcert localhost 127.0.0.1 ::1", serverKeyFile)
	}
	fmt.Println("✅ Server certificate and key found.")

	// --- 2. Find mkcert CA Root ---
	fmt.Println("Finding mkcert CA root directory...")
	caRootDir, err := findMkcertCARoot()
	if err != nil {
		log.Fatalf("❌ Error finding mkcert CA root: %v", err)
	}
	caCertPath := filepath.Join(caRootDir, "rootCA.pem")
	fmt.Printf("✅ Found mkcert CA certificate path: %s\n", caCertPath)

	// --- 3. Load mkcert CA Certificate ---
	fmt.Println("Loading mkcert CA certificate...")
	caCertPEM, err := os.ReadFile(caCertPath)
	if err != nil {
		log.Fatalf("❌ Error reading mkcert CA certificate at %s: %v", caCertPath, err)
	}

	// --- 4. Create Client Certificate Pool ---
	fmt.Println("Creating client certificate pool...")
	clientCertPool := x509.NewCertPool()
	if !clientCertPool.AppendCertsFromPEM(caCertPEM) {
		log.Fatalf("❌ Failed to append mkcert CA certificate to client pool.")
	}
	fmt.Println("✅ Client certificate pool created and mkcert CA added.")

	// --- 5. Configure Server TLS ---
	fmt.Println("Configuring server TLS settings for mTLS...")
	tlsConfig := &tls.Config{
		// Use GetCertificate to load server cert/key on demand (allows rotation if needed)
		GetCertificate: func(*tls.ClientHelloInfo) (*tls.Certificate, error) {
			cert, err := tls.LoadX509KeyPair(serverCertFile, serverKeyFile)
			if err != nil {
				log.Printf("🚨 Error loading server key pair: %v", err)
				return nil, fmt.Errorf("loading server key pair: %w", err)
			}
			return &cert, nil
		},

		// --- mTLS Specific Configuration ---
		ClientAuth: tls.RequireAndVerifyClientCert, // Require clients to present a certificate and verify it
		ClientCAs:  clientCertPool,                 // Use the pool containing the mkcert CA to verify clients

		// --- General TLS Settings ---
		MinVersion: tls.VersionTLS12, // Recommended minimum TLS version
		CurvePreferences: []tls.CurveID{ // Prefer modern elliptic curves
			tls.X25519,
			tls.CurveP256,
		},
	}

	// --- 6. Setup HTTP Server ---
	mux := http.NewServeMux()
	mux.HandleFunc("/", helloHandler) // Register the handler for all paths

	server := &http.Server{
		Addr:         listenAddr,
		Handler:      mux,
		TLSConfig:    tlsConfig,
		ReadTimeout:  5 * time.Second, // Basic timeouts
		WriteTimeout: 10 * time.Second,
		IdleTimeout:  120 * time.Second,
	}

	// --- 7. Start Server ---
	fmt.Printf("🚀 Starting mTLS server on https://localhost%s\n", listenAddr)
	fmt.Println("   (Ensure clients present a certificate signed by your mkcert CA)")

	// We pass empty strings for cert/key files because GetCertificate is defined in TLSConfig
	err = server.ListenAndServeTLS("", "")
	if err != nil {
		// This error will be logged if the server stops unexpectedly
		log.Fatalf("❌ Server failed: %v", err)
	}
}
